### PR TITLE
refactor: CSS cleanup to prepare for stylelint rules

### PR DESCRIPTION
**Pull request by arkadyan**
Precursor to: [Set up CSS linting in reduced_fares project](https://app.asana.com/0/1200240595613188/1201752498907673)

This PR only includes refactoring, no functional changes.

This enables the forthcoming stylelint check to pass: https://github.com/mbta/reduced_fares/actions/runs/2061087447

### CODE REVIEW

**Review by krisrjohnson21 — APPROVED** [review]
✅  Can we confirm that this file will successfully upload in SimpliGov before merging by using a cloned version of each form?

**Comment by arkadyan** [comment]
@krisrjohnson21 That's a good idea. If I create cloned workflows in pre-prod and deploy there does that seem like a sufficient test?

**Comment by krisrjohnson21** [comment]
Yes, that should be perfect @arkadyan!

**Comment by arkadyan** [comment]
I was able to successfully upload both the Youth and Senior CSS files.

**Pull request merged**
