### PR TITLE
test: Update test to match new email address

### PR DESCRIPTION
**Pull request by arkadyan**
This is to merge a test fix into the `remove-emily-from-municipality-data` branch. @krisrjohnson21 please confirm, but I think with this change it relieves the concerns with https://github.com/mbta/reduced_fares/pull/163.

### CODE REVIEW

**Comment by krisrjohnson21** [comment]
Thanks for jumping on this! I am working on a fix for the required-fields test and I'll fold this fix into that test.

**Review by krisrjohnson21 — APPROVED** [review]
✅

**Comment by arkadyan** [comment]
@krisrjohnson21 Updated this to be based on `main` since https://github.com/mbta/reduced_fares/pull/163 was merged, but feel free to cherry-pick it into a different branch/PR if that's easier.

**Comment by arkadyan** [comment]
@krisrjohnson21 Actually I'll just merge this and you can take it from there.

**Pull request merged**
